#!/bin/sh
if [ "$2" == "" ] ; then
	branch=`git branch | grep "*" | awk '{print $2}'`
	if test "${branch:0:7}" = "feature"; then
	    ticket=`git branch | grep "*" | awk '{print $2}' | sed -e "s/[^0-9]//g"`
	    title=`git redmine $ticket`
	    echo "refs $title" > $1
	fi
	if test "${branch:0:7}" = "release"; then
	    version=`git branch | grep "*" | awk '{print $2}' | sed -e "s/[^0-9|.]//g"`
	    echo "refs $version" > $1
	fi
	if test "${branch:0:6}" = "hotfix"; then
	    ticket=`git branch | grep "*" | awk '{print $2}' | sed -e "s/[^0-9]//g"`
	    title=`git redmine $ticket`
	    echo "refs $title" > $1
	fi
fi