[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.git'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  syntax enable
  set background=dark
  let g:solarized_termtrans=1
  au VimEnter * nested colorscheme solarized 
'''

[[plugins]]
repo= 'plasticboy/vim-markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  au BufRead,BufNewFile *.md set filetype=markdown
'''

[[plugins]]
repo= 'kannokanno/previm'

[[plugins]]
repo= 'tyru/open-browser.vim'
